version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 42879:5000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres 
  postgres:
    build: services/postgres
    volumes:
      - ./:/tmp/db
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - 28921:5432

volumes:
        postgres:
        postgres_data:
